[project]
name = "stac-task"
version = "0.2.0"
authors = [
    { name = "Matthew Hanson", email = "matt.a.hanson@gmail.com" },
    { name = "Pete Gadomski", email = "pete.gadomski@gmail.com" },
]
description = "Class interface for running custom algorithms and workflows on STAC items"
readme = "README.md"
requires-python = ">=3.8"
keywords = ["pystac", "imagery", "raster", "catalog", "STAC"]
license = { text = "Apache-2.0" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "importlib_metadata>=4.4; python_version<'3.10'",
    "pydantic>=2",
    "pystac>=1.8",
    "stac-asset>=0.2.2",
]

[project.optional-dependencies]
cli = ["click~=8.1"]
dev = [
    "black~=23.9",
    "codespell~=2.2",
    "ruff==0.0.289",
    "mypy~=1.5",
    "pre-commit~=3.4",
    "pytest~=7.4",
    "pytest-cov~=4.1",
    "types-setuptools~=68.2",
]
examples = ["rio-stac~=0.8.0"]

[project.scripts]
stac-task = "stac_task._cli:cli"

[project.urls]
Issues = "https://github.com/stac-utils/stac-task/issues"
Github = "https://github.com/stac-utils/stac-task"
Changelog = "https://github.com/stac-utils/stac-task/blob/main/CHANGELOG.md"

[tool.mypy]
strict = true

[tool.ruff]
select = ["E", "F", "I", "D", "RUF", "ERA"]
ignore = ["D203", "D212"]

[tool.ruff.per-file-ignores]
"tests/**/*.py" = ["D"]
"examples/**/*.py" = ["D"]

[tool.ruff.pydocstyle]
convention = "google"
